import {root,toolRoot} from './tools.mjs';import {readFile,writeFile} from 'node:fs/promises';import {createHash} from 'node:crypto';import path from 'node:path';
const assets=[
{file:'assets/footage/door-conversation.mp4',source:'https://www.pexels.com/video/couple-having-a-intense-conversation-in-front-of-the-door-5617887/',download:'https://videos.pexels.com/video-files/5617887/5617887-hd_1920_1080_24fps.mp4',creator:'RDNE Stock project',license:'https://www.pexels.com/license/',role:'Fictional short-drama viewing content only, no endorsement or judgement about identifiable actors',transform:'source 1–7s, scale1280w, CFR60 repeated native frames, all-intra H264, no source audio',original:'tmp/drama-source.mp4'},
{file:'assets/footage/coffee-pour.mp4',source:'https://www.pexels.com/video/pouring-black-coffee-into-a-cup-7118100/',download:'https://videos.pexels.com/video-files/7118100/7118100-uhd_2160_3840_25fps.mp4',creator:'Michael Burrows',license:'https://www.pexels.com/license/',role:'Lifestyle actual motion, no brand/user/private data',transform:'source 1–7s, 720x1280, CFR60 repeated native frames, all-intra H264, no audio',original:'tmp/coffee-source.mp4'},
{file:'assets/footage/social-photo.jpg',source:'assets/footage/coffee-pour.mp4',license:'https://www.pexels.com/license/',creator:'Michael Burrows',role:'Generic fictional social photo post, original anonymous caption and avatar',transform:'first frame derivative, no private username'},
{file:'assets/reference/today-quick-start.png',source:'store-assets/captures/en/04-today.png',license:'project-owned shipped UI',role:'Real Release Quick Start sample, 30m is unmodified, not live data',runtimeCaptureSHA:'6e5a82fc60236c5bc9a408207fcd6ad102cacffa',run:'https://github.com/Zhangsfish/Elapse/actions/runs/37501370483',transform:'none; entire PNG proportionally scaled into front-view frame'},
{file:'assets/reference/everwhile-icon.png',source:'App/Assets.xcassets/AppIcon.appiconset/AppIcon.png',license:'project-owned branding',transform:'none'},
{file:'assets/fonts/InterVariable.ttf',source:'https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip#InterVariable.ttf',license:'SIL Open Font License 1.1',version:'4.1',face:'Inter Variable, real weight600, optical-size32 display',redistributed:false},
{file:'review/music.wav',source:'scripts/sound.py',license:'original project composition',bpm:120,sampleRate:48000},
{file:'review/sfx.wav',source:'scripts/sound.py',license:'original project synthesis',sampleRate:48000,onsets:[7.5,9.5,11.5]}
];
for(const a of assets){const b=await readFile(path.join(root,a.file));a.sha256=createHash('sha256').update(b).digest('hex');a.bytes=b.length;if(a.original)a.originalSHA256=createHash('sha256').update(await readFile(path.join(root,a.original))).digest('hex');}
const tools={};for(const name of ['hyperframes','gsap','typescript','esbuild','puppeteer-core']){const p=JSON.parse(await readFile(path.join(toolRoot,'node_modules',name,'package.json')));tools[name]=p.version;}
await writeFile(path.join(root,'ASSET_MANIFEST.json'),JSON.stringify({task:'PROMO-P01',baseSHA:'76838c8bd8659c379314decaa30c07ec0cb1e0ef',licenseChecked:'2026-10-07',assets,tools,privateData:[],renderNetwork:'NONE',fontBinariesCommitted:false,sourceHanSC:{status:'DEFERRED_ZH_AFTER_DIRECTOR_REVIEW',sha256:'df2b90f5bcc6d01dfc964cec5f6d535d6b6aebd26ed7fd79a9c1b3f2112fcb6b',source:'https://raw.githubusercontent.com/adobe-fonts/source-han-sans/2.005R/OTF/SimplifiedChinese/SourceHanSansSC-Bold.otf',face:'Bold700 2.005R'}},null,2)+'\n');
